"""empty message

Revision ID: 913bdb2b4afa
Revises: 25aa196e8f92
Create Date: 2023-09-09 02:09:50.001274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '913bdb2b4afa'
down_revision: Union[str, None] = '25aa196e8f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('command_pitch', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('command_tasks', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('command_interest', sa.Integer(), nullable=True))
    op.drop_column('users', 'commends')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('commends', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'command_interest')
    op.drop_column('users', 'command_tasks')
    op.drop_column('users', 'command_pitch')
    # ### end Alembic commands ###
