"""empty message

Revision ID: a5f6cd3812d9
Revises: 913bdb2b4afa
Create Date: 2023-09-09 02:19:29.460870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f6cd3812d9'
down_revision: Union[str, None] = '913bdb2b4afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('participation_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'participationCount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('participationCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'participation_count')
    # ### end Alembic commands ###
