"""empty message

Revision ID: ddd0223659bb
Revises: 80d04d90573d
Create Date: 2023-09-09 14:02:19.540769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd0223659bb'
down_revision: Union[str, None] = '80d04d90573d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('command_pitch', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('command_tasks', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('command_interest', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('participation_count', sa.Integer(), nullable=True))
    op.drop_column('users', 'command_tasks')
    op.drop_column('users', 'command_pitch')
    op.drop_column('users', 'team_id')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'command_interest')
    op.drop_column('users', 'participation_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('participation_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('command_interest', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('command_pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('command_tasks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'participation_count')
    op.drop_column('profiles', 'rating')
    op.drop_column('profiles', 'team_id')
    op.drop_column('profiles', 'command_interest')
    op.drop_column('profiles', 'command_tasks')
    op.drop_column('profiles', 'command_pitch')
    # ### end Alembic commands ###
